### PR TITLE
added somalia

### PR DESCRIPTION
**Pull request by ArshErgon**
fixed for this issue #85

### CODE REVIEW

**Comment by BenOvermyer** [comment]
@ArshErgon If you want this to count for Hacktoberfest, you should close this PR and open a new one after October 1.

**Comment by ArshErgon** [comment]
Yeah sure

**Comment by BenOvermyer** [comment]
You'll need to fix the code before it will work. Make sure to build and test before submitting pull requests.

**Comment by ArshErgon** [comment]
@BenOvermyer  done, for both of the branches, I forget to add the language inside the namegen.go file, sorry for the delay

**Pull request merged**
