### PR TITLE
Added Irish names

### LINKED ISSUE #83: Add Irish names
Add Irish names to the generator.

See https://en.wikipedia.org/wiki/Irish_name

### PR DESCRIPTION
**Pull request by NevilleMthw**
This resolves #83.

### CODE REVIEW

**Comment by NevilleMthw** [comment]
Hi, @BenOvermyer I think for the PR to count towards Hacktoberfest, it would require you to add the Hacktoberfest-accepted label on it as stated on the website.

**Comment by BenOvermyer** [comment]
@NevilleMthw That's one of the ways it will count, yes. But as long as the repo has the hacktoberfest topic, it will count.

**Comment by NevilleMthw** [comment]
Oh okay, that's fine then. Since I checked the website regarding my progress of this PR and it says not-participating on it so just wondering about that.

**Comment by NevilleMthw** [comment]
Also, I don't think the repo has the hacktoberfest label on it, if I am correct. I just see three labels on it.

**Comment by BenOvermyer** [comment]
You're right. I've corrected that... hopefully it gives you credit now. Otherwise, we'll have to figure out something.

**Comment by NevilleMthw** [comment]
Yes, it works now. Thank you.

**Pull request merged**
